[package]
name = "plasmite"
version = "0.1.0"
edition = "2024"
license = "MIT"
description = "Plasmite CLI and library."
repository = "https://github.com/YOUR_GITHUB/plasmite"
readme = "README.md"

[lib]
path = "src/lib.rs"

[[bin]]
name = "plasmite"
path = "src/main.rs"

[dependencies]
fs2 = "0.4"
memmap2 = "0.9"

[dev-dependencies]
tempfile = "3"
