[package]
name = "plasmite"
version = "0.1.0"
edition = "2024"
license = "MIT"
description = "Plasmite CLI and library."
repository = "https://github.com/YOUR_GITHUB/plasmite"
readme = "README.md"
build = "build.rs"

[lib]
path = "src/lib.rs"

[[bin]]
name = "plasmite"
path = "src/main.rs"

[dependencies]
clap = { version = "4", features = ["derive"] }
fs2 = "0.4"
memmap2 = "0.9"
libc = "0.2"
serde_json = "1"

[dev-dependencies]
tempfile = "3"

[build-dependencies]
cc = "1"
